//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKTFBicycleRenting.Models
{
    using System;
    using System.Collections.Generic;
    //Rent Class Defination
    public partial class Rent
    {
        public int Rent_id { get; set; }
        public string Username { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Admin_id { get; set; }
        public int Bicycle_id { get; set; }
    }
}
